[project]
name = "JupyterNBs"
version = "0.1.0"
description = "Marimo para jupyter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.17",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "plotly>=6.3.0",
]
